language: java
jdk: openjdk10
env:
   - COVERAGE=0.35 ./gradlew test jacocoTestCoverageVerification
script:
    - echo 'testing'
    - ./gradlew test

after_success:
  - ./gradlew jacocoTestReport
  - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'

deploy:
  if: COVERAGE
    - echo 'WIP'
